#!/usr/bin/env python3
"""Generate deterministic MkDocs support-coverage tables.

The generated page is intentionally source-only: it inventories the checked-in
OpenOCD Tcl/SVD/support files without importing a YAML dependency or probing
hardware.  CI uses ``--check`` so documentation cannot silently drift from the
repository layout.
"""

from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUTPUT = ROOT / "docs" / "reference" / "support-matrix.md"


def grouped_files(base: Path, suffix: str) -> dict[str, list[str]]:
    groups: dict[str, list[str]] = defaultdict(list)
    for path in sorted(base.rglob(f"*{suffix}")):
        relative = path.relative_to(ROOT).as_posix()
        local = path.relative_to(base)
        group = local.parts[0] if len(local.parts) > 1 else "(root)"
        groups[group].append(relative)
    return dict(sorted(groups.items()))


def table(title: str, groups: dict[str, list[str]]) -> list[str]:
    lines = [f"## {title}", "", "| Area | Files | Representative entries |", "|---|---:|---|"]
    for group, files in groups.items():
        examples = ", ".join(f"`{item}`" for item in files[:3])
        lines.append(f"| `{group}` | {len(files)} | {examples} |")
    lines.append("")
    return lines


def render() -> str:
    board = grouped_files(ROOT / "tcl" / "board", ".cfg")
    fpga = grouped_files(ROOT / "tcl" / "fpga", ".cfg")
    cpld = grouped_files(ROOT / "tcl" / "cpld", ".cfg")
    interfaces = grouped_files(ROOT / "tcl" / "interface", ".cfg")
    svd = grouped_files(ROOT / "svd", ".svd")
    metadata = grouped_files(ROOT / "support" / "boards", "board.yml")

    lines = [
        "# Support matrix",
        "",
        "<!-- Generated by tools/docs/generate_support_tables.py; do not edit manually. -->",
        "",
        "This page is generated from the checked-in runtime configuration and support metadata. "
        "It provides a quick coverage overview; the authoritative implementation remains under "
        "`tcl/`, `src/`, `support/`, and `svd/`.",
        "",
        "| Asset family | Files | Source area |",
        "|---|---:|---|",
        f"| Board configurations | {sum(map(len, board.values()))} | `tcl/board/` |",
        f"| FPGA configurations | {sum(map(len, fpga.values()))} | `tcl/fpga/` |",
        f"| CPLD configurations | {sum(map(len, cpld.values()))} | `tcl/cpld/` |",
        f"| Interface/cable configurations | {sum(map(len, interfaces.values()))} | `tcl/interface/` |",
        f"| Curated SVD files | {sum(map(len, svd.values()))} | `svd/` |",
        f"| Board metadata entries | {sum(map(len, metadata.values()))} | `support/boards/` |",
        "",
    ]
    lines += table("Board configurations", board)
    lines += table("FPGA configurations", fpga)
    lines += table("CPLD configurations", cpld)
    lines += table("Interface and cable configurations", interfaces)
    lines += table("Curated SVD files", svd)
    lines += table("Board metadata", metadata)
    return "\n".join(lines).rstrip() + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the generated page is stale")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            print(f"{OUTPUT} is stale; run tools/docs/generate_support_tables.py")
            return 1
        return 0
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Generated {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
