# SPDX-License-Identifier: GPL-2.0-or-later
<#
.SYNOPSIS
Generate native OpenOCD AVR support metadata from an AVR catalog file.

.DESCRIPTION
Parses an AVR catalog in AVRDUDE avrdude.conf / avrdude.conf.in syntax and
writes compact YAML metadata under support/catalogs/avrdude. The generated
files are an index for OpenOCD packaging, documentation, and future native
backend triage.

The parser intentionally avoids external dependencies so it works in a fresh
Windows development shell.
#>

[CmdletBinding()]
param(
  [string] $Root = '',
  [string] $Config = '',
  [string] $OutputDirectory = '',
  [switch] $Quiet
)

$ErrorActionPreference = 'Stop'

function Resolve-RepositoryRoot {
  param([string] $RootValue)

  if ($RootValue -ne '') {
    return (Resolve-Path $RootValue).Path
  }

  $scriptPath = $PSCommandPath
  if ($scriptPath -eq $null -or $scriptPath -eq '') {
    $scriptPath = $MyInvocation.MyCommand.Path
  }
  if ($scriptPath -eq $null -or $scriptPath -eq '') {
    throw 'Unable to determine script path; pass -Root explicitly.'
  }
  return (Resolve-Path (Join-Path (Split-Path -Parent $scriptPath) '..\..')).Path
}

function Find-AvrdudeConfig {
  param([string] $ExplicitConfig)

  if ($ExplicitConfig -ne '') {
    return (Resolve-Path $ExplicitConfig).Path
  }

  $candidates = New-Object System.Collections.Generic.List[string]
  if ($env:AVRDUDE_CONF -ne $null -and $env:AVRDUDE_CONF -ne '') {
    $candidates.Add($env:AVRDUDE_CONF)
  }

  $command = Get-Command avrdude -ErrorAction SilentlyContinue
  if ($command -ne $null) {
    $toolRoot = Split-Path -Parent (Split-Path -Parent $command.Source)
    $candidates.Add((Join-Path $toolRoot 'etc\avrdude.conf'))
    $candidates.Add((Join-Path (Split-Path -Parent $command.Source) 'avrdude.conf'))
  }

  $candidates.Add('artifacts\vendor-sources\avrdude\src\avrdude.conf.in')
  $candidates.Add('src\avrdude.conf.in')

  foreach ($candidate in $candidates) {
    if ($candidate -ne $null -and $candidate -ne '' -and (Test-Path -LiteralPath $candidate)) {
      return (Resolve-Path $candidate).Path
    }
  }

  throw 'Unable to find avrdude.conf. Pass -Config or set AVRDUDE_CONF.'
}

function Remove-AvrdudeComment {
  param([string] $Line)

  $inQuote = $false
  for ($i = 0; $i -lt $Line.Length; $i++) {
    $ch = $Line[$i]
    if ($ch -eq '"') {
      $inQuote = -not $inQuote
    } elseif ($ch -eq '#' -and -not $inQuote) {
      return $Line.Substring(0, $i)
    }
  }
  return $Line
}

function Get-QuotedOrBareValues {
  param([string] $Value)

  $items = New-Object System.Collections.Generic.List[string]
  foreach ($match in [regex]::Matches($Value, '"([^"]+)"')) {
    $items.Add($match.Groups[1].Value)
  }
  if ($items.Count -gt 0) {
    return @($items)
  }

  foreach ($item in ($Value -split ',')) {
    $trimmed = $item.Trim()
    if ($trimmed -ne '') {
      $items.Add($trimmed)
    }
  }
  return @($items)
}

function Get-Scalar {
  param(
    [string] $Text,
    [string] $Name
  )

  $escapedName = [regex]::Escape($Name)
  $match = [regex]::Match($Text, "(?m)^\s*${escapedName}\s*=\s*([^;]+);")
  if (-not $match.Success) {
    return ''
  }

  $value = $match.Groups[1].Value.Trim()
  $quoted = [regex]::Match($value, '^"([^"]*)"$')
  if ($quoted.Success) {
    return $quoted.Groups[1].Value
  }
  return $value
}

function Get-Boolean {
  param(
    [string] $Text,
    [string] $Name
  )

  $value = (Get-Scalar -Text $Text -Name $Name).ToLowerInvariant()
  if ($value -eq 'yes') { return $true }
  if ($value -eq 'no') { return $false }
  return $null
}

function ConvertTo-YamlScalar {
  param([object] $Value)

  if ($Value -eq $null) { return 'null' }
  if ($Value -is [bool]) {
    if ($Value) { return 'true' }
    return 'false'
  }

  $text = [string] $Value
  if ($text -match '^[A-Za-z0-9_.:+/@%-]+$') {
    return $text
  }
  return "'$($text.Replace("'", "''"))'"
}

function ConvertTo-CString {
  param([object] $Value)

  if ($Value -eq $null) {
    return '""'
  }
  $text = [string] $Value
  $text = $text.Replace('\', '\\').Replace('"', '\"')
  $text = $text.Replace("`r", '\r').Replace("`n", '\n').Replace("`t", '\t')
  return '"' + $text + '"'
}

function Join-CatalogList {
  param([object] $Value)

  if ($Value -eq $null) {
    return ''
  }
  if ($Value -is [array]) {
    return ($Value | Where-Object { $_ -ne $null -and $_ -ne '' }) -join ','
  }
  return [string] $Value
}

function Write-CatalogData {
  param(
    [string] $Path,
    [array] $Parts,
    [array] $Programmers,
    [string] $SourceName,
    [string] $SourceSha256
  )

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('// SPDX-License-Identifier: GPL-2.0-or-later')
  $lines.Add('// Generated by tools/support/generate-avr-catalog.ps1.')
  $lines.Add('// Do not edit by hand; regenerate from avrdude.conf.')
  $lines.Add('')
  $lines.Add('#ifdef HAVE_CONFIG_H')
  $lines.Add('#include "config.h"')
  $lines.Add('#endif')
  $lines.Add('')
  $lines.Add('#include "avr_catalog.h"')
  $lines.Add('')
  $lines.Add("const char avr_catalog_source[] = $(ConvertTo-CString $SourceName);")
  $lines.Add("const char avr_catalog_source_sha256[] = $(ConvertTo-CString $SourceSha256);")
  $lines.Add('')
  $lines.Add('const struct avr_catalog_mcu avr_catalog_mcus[] = {')
  foreach ($part in $Parts) {
    $lines.Add("`t{ $(ConvertTo-CString $part['id']), $(ConvertTo-CString (Join-CatalogList $part['aliases'])), $(ConvertTo-CString $part['description']), $(ConvertTo-CString $part['parent']), $(ConvertTo-CString $part['signature']), $(ConvertTo-CString (Join-CatalogList $part['interfaces'])), $(ConvertTo-CString (Join-CatalogList $part['memories'])) },")
  }
  $lines.Add('};')
  $lines.Add('const size_t avr_catalog_mcu_count = sizeof(avr_catalog_mcus) / sizeof(avr_catalog_mcus[0]);')
  $lines.Add('')
  $lines.Add('const struct avr_catalog_programmer avr_catalog_programmers[] = {')
  foreach ($programmer in $Programmers) {
    $lines.Add("`t{ $(ConvertTo-CString $programmer['id']), $(ConvertTo-CString (Join-CatalogList $programmer['aliases'])), $(ConvertTo-CString $programmer['description']), $(ConvertTo-CString $programmer['parent']), $(ConvertTo-CString $programmer['type']), $(ConvertTo-CString $programmer['prog_modes']), $(ConvertTo-CString $programmer['connection_type']), $(ConvertTo-CString $programmer['usbvid']), $(ConvertTo-CString $programmer['usbpid']), $(ConvertTo-CString $programmer['usbvendor']), $(ConvertTo-CString $programmer['usbproduct']) },")
  }
  $lines.Add('};')
  $lines.Add('const size_t avr_catalog_programmer_count = sizeof(avr_catalog_programmers) / sizeof(avr_catalog_programmers[0]);')

  Set-Content -LiteralPath $Path -Value $lines -Encoding ascii
}

function Write-YamlCatalog {
  param(
    [string] $Path,
    [string] $Kind,
    [array] $Entries,
    [string] $SourceName,
    [string] $SourceSha256
  )

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add('# SPDX-License-Identifier: GPL-2.0-or-later')
  $lines.Add('# Generated by tools/support/generate-avr-catalog.ps1.')
  $lines.Add('# Do not edit entries by hand; regenerate from avrdude.conf.')
  $lines.Add("kind: $Kind")
  $lines.Add("source: $SourceName")
  $lines.Add("source_sha256: $SourceSha256")
  $lines.Add("count: $($Entries.Count)")
  $lines.Add('entries:')

  foreach ($entry in $Entries) {
    $lines.Add("  - id: $(ConvertTo-YamlScalar $entry.id)")
    if ($entry.aliases.Count -gt 0) {
      $lines.Add('    aliases:')
      foreach ($alias in $entry.aliases) {
        $lines.Add("      - $(ConvertTo-YamlScalar $alias)")
      }
    }
    foreach ($key in $entry.Keys) {
      if ($key -eq 'id' -or $key -eq 'aliases') { continue }
      $value = $entry[$key]
      if ($value -eq $null -or $value -eq '' -or ($value -is [array] -and $value.Count -eq 0)) {
        continue
      }
      if ($value -is [array]) {
        $lines.Add("    ${key}:")
        foreach ($item in $value) {
          $lines.Add("      - $(ConvertTo-YamlScalar $item)")
        }
      } else {
        $lines.Add("    ${key}: $(ConvertTo-YamlScalar $value)")
      }
    }
  }

  Set-Content -LiteralPath $Path -Value $lines -Encoding ascii
}

function Convert-BlockToEntry {
  param(
    [string] $Kind,
    [string[]] $Block
  )

  $text = ($Block | ForEach-Object { Remove-AvrdudeComment $_ }) -join "`n"
  $idMatch = [regex]::Match($text, '(?m)^\s*id\s*=\s*([^;]+);')
  if (-not $idMatch.Success) {
    return $null
  }

  $ids = @(Get-QuotedOrBareValues $idMatch.Groups[1].Value)
  if ($ids.Count -eq 0) {
    return $null
  }

  $entry = [ordered]@{
    id = $ids[0]
    aliases = @($ids | Select-Object -Skip 1)
    description = Get-Scalar -Text $text -Name 'desc'
  }

  if ($Kind -eq 'part') {
    $parentMatch = [regex]::Match($text, '(?m)^\s*part\s+parent\s+"?([^";\s]+)"?')
    if ($parentMatch.Success) {
      $entry.parent = $parentMatch.Groups[1].Value
    }

    $signature = Get-Scalar -Text $text -Name 'signature'
    if ($signature -ne '') {
      $entry.signature = ($signature -replace '\s+', ' ').Trim()
    }

    $interfaces = New-Object System.Collections.Generic.List[string]
    foreach ($name in @('jtag', 'debugwire', 'pdi', 'updi', 'tpi')) {
      $enabled = Get-Boolean -Text $text -Name "has_$name"
      if ($enabled -eq $true) {
        $interfaces.Add($name)
      }
    }
    $entry.interfaces = @($interfaces)

    $memories = New-Object System.Collections.Generic.List[string]
    foreach ($match in [regex]::Matches($text, '(?m)^\s*memory\s+"([^"]+)"')) {
      if (-not $memories.Contains($match.Groups[1].Value)) {
        $memories.Add($match.Groups[1].Value)
      }
    }
    $entry.memories = @($memories)
  } else {
    $parentMatch = [regex]::Match($text, '(?m)^\s*(?:programmer\s+)?parent\s+"?([^";\s]+)"?')
    if ($parentMatch.Success) {
      $entry.parent = $parentMatch.Groups[1].Value
    }
    foreach ($field in @('type', 'prog_modes', 'connection_type', 'usbvid', 'usbpid', 'usbvendor', 'usbproduct')) {
      $value = Get-Scalar -Text $text -Name $field
      if ($value -ne '') {
        $entry[$field] = ($value -replace '\s+', ' ').Trim()
      }
    }
  }

  return $entry
}

$rootPath = Resolve-RepositoryRoot -RootValue $Root
$configPath = Find-AvrdudeConfig -ExplicitConfig $Config
if ($OutputDirectory -eq '') {
  $OutputDirectory = Join-Path $rootPath 'support\catalogs\avrdude'
}
$outputPath = New-Item -ItemType Directory -Force -Path $OutputDirectory

$parts = New-Object System.Collections.Generic.List[object]
$programmers = New-Object System.Collections.Generic.List[object]
$currentKind = ''
$currentBlock = New-Object System.Collections.Generic.List[string]

foreach ($line in Get-Content -LiteralPath $configPath) {
  $clean = (Remove-AvrdudeComment $line).Trim()
  if ($clean -match '^(part|programmer)(\s|$)') {
    if ($currentKind -ne '' -and $currentBlock.Count -gt 0) {
      $entry = Convert-BlockToEntry -Kind $currentKind -Block @($currentBlock)
      if ($entry -ne $null) {
        if ($currentKind -eq 'part') { $parts.Add($entry) } else { $programmers.Add($entry) }
      }
    }
    $currentKind = $Matches[1]
    $currentBlock.Clear()
    $currentBlock.Add($line)
  } elseif ($currentKind -ne '') {
    $currentBlock.Add($line)
  }
}

if ($currentKind -ne '' -and $currentBlock.Count -gt 0) {
  $entry = Convert-BlockToEntry -Kind $currentKind -Block @($currentBlock)
  if ($entry -ne $null) {
    if ($currentKind -eq 'part') { $parts.Add($entry) } else { $programmers.Add($entry) }
  }
}

$sourceHash = (Get-FileHash -LiteralPath $configPath -Algorithm SHA256).Hash.ToLowerInvariant()
$sourceName = Split-Path -Leaf $configPath
$sortedParts = @($parts | Sort-Object { $_['id'] })
$sortedProgrammers = @($programmers | Sort-Object { $_['id'] })
Write-YamlCatalog -Path (Join-Path $outputPath 'parts.yml') -Kind 'openocd-mcus' -Entries $sortedParts -SourceName $sourceName -SourceSha256 $sourceHash
Write-YamlCatalog -Path (Join-Path $outputPath 'programmers.yml') -Kind 'openocd-programmers' -Entries $sortedProgrammers -SourceName $sourceName -SourceSha256 $sourceHash
Write-CatalogData -Path (Join-Path $rootPath 'src\avr\avr_catalog_data.c') -Parts $sortedParts -Programmers $sortedProgrammers -SourceName $sourceName -SourceSha256 $sourceHash

if (-not $Quiet) {
  Write-Host "AVRDUDE config: $configPath"
  Write-Host "parts: $($parts.Count)"
  Write-Host "programmers: $($programmers.Count)"
  Write-Host "output: $($outputPath.FullName)"
}
