services:
  openocd:
    build:
      context: .
      dockerfile: docker/Dockerfile
      args:
        CONFIGURE_FLAGS: ${CONFIGURE_FLAGS:---enable-ftdi --enable-stlink --enable-cmsis-dap --enable-jlink --enable-jimtcl-maintainer --enable-internal-jimtcl}
    container_name: openocd
    restart: unless-stopped
    privileged: true
    devices:
      - /dev/bus/usb:/dev/bus/usb
    volumes:
      - ./docker/data/config:/work/config:ro
      - ./docker/data/examples:/work/examples:ro
    ports:
      - "3333:3333" # GDB
      - "4444:4444" # Telnet
      - "6666:6666" # Tcl
    environment:
      OPENOCD_BINDTO: 0.0.0.0
    command:
      - -f
      - config/default.cfg
