[project]
vendor = "Microchip"
output_dir = "svd"
source_dir = "sources"
metadata_dir = "metadata"

[[packs]]
name = "dsPIC30F_DFP"
version = "1.6.395"
url = "https://packs.download.microchip.com/Microchip.dsPIC30F_DFP.1.6.395.atpack"
devices = ["dsPIC30F5011"]

[[packs]]
name = "dsPIC33F-GP-MC_DFP"
version = "1.5.373"
url = "https://packs.download.microchip.com/Microchip.dsPIC33F-GP-MC_DFP.1.5.373.atpack"
devices = ["dsPIC33FJ128MC802", "dsPIC33FJ128MC804"]

[[packs]]
name = "dsPIC33E-GM-GP-MC-GU-MU_DFP"
version = "1.7.401"
url = "https://packs.download.microchip.com/Microchip.dsPIC33E-GM-GP-MC-GU-MU_DFP.1.7.401.atpack"
devices = ["dsPIC33EP128GM604"]
